/**
 * 03 — Route the record.
 *
 * SIMULATED DATA. The incident below did not happen. Every artifact was written
 * for this page. None of it is drawn from any real firm, product or matter.
 * The screen that shows these cards says so.
 *
 * What is NOT simulated is the doctrine used to grade them. Every discovery
 * outcome cites an authority the paper names, and the reasons are the paper's.
 */

export type Bin = 'one' | 'two' | 'three' | 'none'

/** The record a later engineer needs. Paper §3.1.2 and §3.2.1. */
export type RecordField =
  | 'versions'
  | 'promptsOutputs'
  | 'retrievalTools'
  | 'guardrailDecisions'
  | 'driftCalibration'
  | 'thresholds'
  | 'operatingConditions'

/**
 * What happens to an artifact if the reader decides not to write it down.
 *  impossible  — instrumentation generated it; the decision has no effect
 *  spoliation  — it exists, and a preservation duty may have attached
 *  uncreated   — it would simply never exist, and the knowledge goes with it
 */
export type SuppressionEffect = 'impossible' | 'spoliation' | 'uncreated'

export interface Artifact {
  readonly id: string
  readonly kind: string
  readonly source: string
  readonly timestamp: string
  readonly author: string
  readonly title: string
  /** The artifact's actual text. */
  readonly text: string
  /** Generated by instrumentation rather than by a person. */
  readonly autoCaptured: boolean
  /** Carries fault attribution, harm characterisation or causal assertion. */
  readonly faultLanguage: boolean
  /** Carries counsel's legal judgment: exposure, causation, duty. */
  readonly legalAnalysis: boolean
  readonly suppression: SuppressionEffect
  /** Which parts of the reconstructable record this artifact supplies. */
  readonly supplies: readonly RecordField[]
  /** Where the architecture puts it. Used to run the model strategies, never to mark the reader. */
  readonly properBin: Bin
}

export const scenario = {
  heading: 'A deployed assistant, a retrieval layer, and a guardrail that fired late.',
  lines: [
    'An assistant with a retrieval layer and a safety classifier has been in production for four months.',
    'A user reports that it returned instructions that harmed them.',
    'Telemetry shows the guardrail fired 1.8 seconds after the output had already been served.',
  ],
  note: 'Fifteen artifacts exist, or are about to. You decide where each one goes.',
} as const

export const bins = [
  {
    id: 'one',
    n: '1',
    name: 'Channel One',
    sub: 'The factual record',
    hint: 'Automatic, contemporaneous, schema-bound, immutable. Discoverable by design.',
  },
  {
    id: 'two',
    n: '2',
    name: 'Channel Two',
    sub: 'Privileged legal analysis',
    hint: 'Counsel and safety review, working jointly, entered through a pre-committed tripwire.',
  },
  {
    id: 'three',
    n: '3',
    name: 'Channel Three',
    sub: 'Remediation',
    hint: 'Engineering instructions, stripped of the causal and normative reasoning that produced them.',
  },
  {
    id: 'none',
    n: '4',
    name: 'Do not write it down',
    sub: 'Suppress it',
    hint: 'The strategy the Pinto taught. Try it and see what it actually buys you.',
  },
] as const satisfies readonly { id: Bin; n: string; name: string; sub: string; hint: string }[]

/** The reconstructable record, and what is lost when a field is missing. */
export const recordFields: readonly {
  readonly id: RecordField
  readonly label: string
  readonly missingConsequence: string
}[] = [
  {
    id: 'versions',
    label: 'Model and deployment version',
    missingConsequence:
      'Reproduction is system-state dependent, and the serving stack has since changed. Nobody can say which system produced the output.',
  },
  {
    id: 'promptsOutputs',
    label: 'Prompts and outputs',
    missingConsequence:
      'The event cannot be replayed. Inference is stochastic, so a later run does not recreate it.',
  },
  {
    id: 'retrievalTools',
    label: 'Retrieval and tool activity',
    missingConsequence:
      'The failure cannot be attributed among the model, the retrieval layer and the tools. Deployment context may itself have been causal.',
  },
  {
    id: 'guardrailDecisions',
    label: 'Guardrail decisions',
    missingConsequence:
      'No record of whether the guardrail fired, or when. The 1.8-second interval, the whole point of the incident, is gone.',
  },
  {
    id: 'driftCalibration',
    label: 'Drift and calibration measures',
    missingConsequence:
      'A recurring failure mode cannot be told apart from expected variation. The relevant unit of evidence is distributional, and the distribution is missing.',
  },
  {
    id: 'thresholds',
    label: 'Threshold values',
    missingConsequence:
      'No baseline against which to write a regression test, so the incident cannot become a standing check on every later release.',
  },
  {
    id: 'operatingConditions',
    label: 'Material operating conditions',
    missingConsequence:
      'The deployment conditions surrounding the failure are gone, and individually reliable components can interact unsafely.',
  },
]

/** Fifteen artifacts. The mix is what the grading depends on. */
export const deck: readonly Artifact[] = [
  {
    id: 'tel-inference',
    kind: 'Auto-captured telemetry',
    source: 'otel · gen_ai.inference',
    timestamp: '2026-07-14 14:22:07.331Z',
    author: 'Instrumentation',
    title: 'Inference event, classifier score against threshold',
    text: 'session=a9f1c2 model=asst-4.2 policy_version=2026.07.3 clf_confidence=0.31 deploy_threshold=0.60 output_served=true retrieval_docs=4 tool_calls=1 corpus=kb-2026.05',
    autoCaptured: true,
    faultLanguage: false,
    legalAnalysis: false,
    suppression: 'impossible',
    supplies: ['versions', 'promptsOutputs', 'retrievalTools'],
    properBin: 'one',
  },
  {
    id: 'tel-guardrail',
    kind: 'Guardrail decision log',
    source: 'otel · safety.guardrail',
    timestamp: '2026-07-14 14:22:09.173Z',
    author: 'Instrumentation',
    title: 'Guardrail activation, rule id and latency',
    text: 'rule=SR-114 action=block latency_ms=1842 relative_to=output_served state=post_hoc',
    autoCaptured: true,
    faultLanguage: false,
    legalAnalysis: false,
    suppression: 'impossible',
    supplies: ['guardrailDecisions'],
    properBin: 'one',
  },
  {
    id: 'tel-drift',
    kind: 'Drift metric',
    source: 'monitoring · weekly slice report',
    timestamp: '2026-07-13 00:00Z',
    author: 'Instrumentation',
    title: 'Distributional shift on a named input slice',
    text: 'slice=health_advice_longform psi=0.24 wow_delta=+0.09 window=7d n=41,882',
    autoCaptured: true,
    faultLanguage: false,
    legalAnalysis: false,
    suppression: 'impossible',
    supplies: ['driftCalibration'],
    properBin: 'one',
  },
  {
    id: 'redteam',
    kind: 'Prior red-team finding',
    source: 'safety review · adversarial testing',
    timestamp: '2026-04-02',
    author: 'Safety review function',
    title: 'Adversarial testing result, three months before the incident',
    text: 'Long-form health advice prompts defeated the classifier in 7 of 40 trials at confidence below 0.35. Recommended lowering the deployment threshold on this slice. Status at time of incident: open.',
    autoCaptured: false,
    faultLanguage: false,
    legalAnalysis: false,
    suppression: 'spoliation',
    supplies: ['thresholds', 'driftCalibration'],
    properBin: 'one',
  },
  {
    id: 'user-report',
    kind: 'User harm report',
    source: 'support · inbound',
    timestamp: '2026-07-16 09:41Z',
    author: 'User',
    title: 'The only evidence of the failure that arrived outside instrumentation',
    text: 'The user states they followed the assistant’s instructions and were harmed. They give the date, the approximate time, and the substance of the exchange.',
    autoCaptured: false,
    faultLanguage: false,
    legalAnalysis: false,
    suppression: 'spoliation',
    supplies: ['operatingConditions'],
    properBin: 'one',
  },
  {
    id: 'slack',
    kind: 'Engineer message, fault language',
    source: 'chat · #eng-safety',
    timestamp: '2026-07-16 10:04Z',
    author: 'Engineer',
    title: 'Written in the first ten minutes, in the wrong register',
    text: '“the guardrail obviously failed here, we knew this could happen — the red team flagged this exact thing in April and we shipped anyway”',
    autoCaptured: false,
    faultLanguage: true,
    legalAnalysis: false,
    suppression: 'spoliation',
    supplies: [],
    properBin: 'one',
  },
  {
    id: 'postmortem',
    kind: 'Draft postmortem narrative',
    source: 'incident · draft',
    timestamp: '2026-07-17',
    author: 'Incident owner',
    title: 'Mixes observation with causal speculation',
    text: 'Records the timeline and the measurements accurately, then adds that the late guardrail activation “was caused by” an unreviewed threshold and that the outcome “was foreseeable given the April findings”.',
    autoCaptured: false,
    faultLanguage: true,
    legalAnalysis: false,
    suppression: 'uncreated',
    supplies: ['guardrailDecisions', 'operatingConditions'],
    properBin: 'one',
  },
  {
    id: 'counsel-email',
    kind: 'Counsel email',
    source: 'legal · to safety review',
    timestamp: '2026-07-17 08:12Z',
    author: 'Counsel',
    title: 'Request for analysis of exposure',
    text: 'Counsel asks the safety review function to assess, for the purpose of legal advice, whether the event caused legally cognisable harm, whether a reporting duty has arisen, and what remediation options are available.',
    autoCaptured: false,
    faultLanguage: false,
    legalAnalysis: true,
    suppression: 'uncreated',
    supplies: [],
    properBin: 'two',
  },
  {
    id: 'rca',
    kind: 'Root-cause analysis, counsel-directed',
    source: 'legal · joint working session',
    timestamp: '2026-07-21',
    author: 'Counsel and safety engineering',
    title: 'Conditional risk weighed against total risk',
    text: 'Counsel and safety engineers jointly assess the causal chain, weigh the conditional risk on the affected slice against total risk across the deployed life of the system, and consider whether a feasible alternative design existed in April.',
    autoCaptured: false,
    faultLanguage: true,
    legalAnalysis: true,
    suppression: 'uncreated',
    supplies: [],
    properBin: 'two',
  },
  {
    id: 'liability',
    kind: 'Liability assessment',
    source: 'legal · privileged memorandum',
    timestamp: '2026-07-23',
    author: 'Counsel',
    title: 'Explicit exposure estimate',
    text: 'An estimate of litigation exposure arising from the incident and from the open April finding, together with counsel’s advice on which remedial measures to undertake and in what order.',
    autoCaptured: false,
    faultLanguage: true,
    legalAnalysis: true,
    suppression: 'uncreated',
    supplies: [],
    properBin: 'two',
  },
  {
    id: 'evaluator',
    kind: 'External evaluator engagement',
    source: 'legal · retained expert',
    timestamp: '2026-07-24',
    author: 'Outside evaluator, retained by counsel',
    title: 'An independent technical expert, engaged by counsel',
    text: 'An outside evaluator is retained to characterise the failure mode on the affected slice. The engagement letter states that the work is to inform counsel’s legal advice.',
    autoCaptured: false,
    faultLanguage: false,
    legalAnalysis: true,
    suppression: 'uncreated',
    supplies: ['driftCalibration'],
    properBin: 'two',
  },
  {
    id: 'jira-clean',
    kind: 'Jira ticket, clean',
    source: 'eng · SAFE-2291',
    timestamp: '2026-07-25',
    author: 'Safety engineering',
    title: 'A work order an engineer can act on',
    text: 'Add regression test for slice health_advice_longform at confidence < 0.35. Lower deploy_threshold on this slice to 0.75. Owner: platform-safety. Release gate: blocks 2026.08.0.',
    autoCaptured: false,
    faultLanguage: false,
    legalAnalysis: false,
    suppression: 'uncreated',
    supplies: ['thresholds', 'driftCalibration'],
    properBin: 'three',
  },
  {
    id: 'jira-dirty',
    kind: 'Jira ticket, contaminated',
    source: 'eng · SAFE-2292',
    timestamp: '2026-07-25',
    author: 'Safety engineering',
    title: 'The same fix, carrying a conclusion it does not need',
    text: 'Add regression test for slice health_advice_longform and lower the deployment threshold, because the model was defective and the April finding should have been actioned before release.',
    autoCaptured: false,
    faultLanguage: true,
    legalAnalysis: false,
    suppression: 'uncreated',
    supplies: ['thresholds'],
    properBin: 'three',
  },
  {
    id: 'regulator',
    kind: 'Regulator-facing factual report',
    source: 'compliance · serious incident report',
    timestamp: '2026-07-28',
    author: 'Compliance, from Channel One facts',
    title: 'Drawn from the factual record, and nothing else',
    text: 'A factual account of what the system did, assembled from telemetry: versions, timestamps, classifier scores against thresholds, guardrail activation and latency, and the affected slice.',
    autoCaptured: false,
    faultLanguage: false,
    legalAnalysis: false,
    suppression: 'uncreated',
    supplies: ['versions', 'guardrailDecisions', 'thresholds'],
    properBin: 'one',
  },
  {
    id: 'board',
    kind: 'Board briefing',
    source: 'governance · risk committee',
    timestamp: '2026-08-04',
    author: 'Safety review to the board',
    title: 'Residual risk, for the people who must accept it',
    text: 'States the severity level, the likelihood of recurrence, and the risk exposure denominator, so the board or its risk committee can decide whether the residual risk is acceptable.',
    autoCaptured: false,
    faultLanguage: false,
    legalAnalysis: false,
    suppression: 'uncreated',
    supplies: [],
    properBin: 'one',
  },
]

/**
 * The doctrine, per artifact, for a privilege claim in Channel Two.
 *
 * Every pierce and every survival names its authority and gives one line of
 * reasoning, as the paper's own treatment does. This block is the auditable
 * heart of the exercise: a reviewer can check it against §1.2.2 without
 * reading a line of the grading code.
 */
export interface PrivilegeRuling {
  readonly survives: boolean
  readonly authority: string
  readonly reason: string
  /** An additional caution that belongs on the surface, not in a footnote. */
  readonly caveat?: string
}

export const privilegeRulings: Readonly<Record<string, PrivilegeRuling>> = {
  'tel-inference': {
    survives: false,
    authority: 'In re Capital One (2020)',
    reason:
      'Telemetry generated automatically in the ordinary course would have existed regardless of any litigation, so routing it through counsel does not make it privileged.',
  },
  'tel-guardrail': {
    survives: false,
    authority: 'In re Capital One (2020)',
    reason:
      'The guardrail log is instrumentation output. Substantially similar work would have been performed in the ordinary course.',
  },
  'tel-drift': {
    survives: false,
    authority: "In re Rutter's (2021)",
    reason:
      'Weekly distributional monitoring is routine business activity, and treating it as an investigation for counsel does not change what it is.',
  },
  redteam: {
    survives: false,
    authority: "In re Rutter's (2021)",
    reason:
      'Adversarial testing carried out three months before the incident was routine safety work, created when no litigation was anticipated.',
  },
  'user-report': {
    survives: false,
    authority: 'Upjohn Co. v. United States (1981)',
    reason:
      'Privilege protects communications made to obtain legal advice and never the underlying facts. A user’s account of harm is a fact.',
  },
  slack: {
    survives: false,
    authority: 'Guo Wengui v. Clark Hill (2021)',
    reason:
      'A contemporaneous engineering message is an ordinary business record, and copying counsel does not convert it into privileged material.',
  },
  postmortem: {
    survives: false,
    authority: 'In re Capital One (2020)',
    reason:
      'A postmortem the firm would have written anyway is ordinary-course work, and sending it to counsel afterwards does not protect the causal speculation inside it.',
  },
  'counsel-email': {
    survives: true,
    authority: 'Upjohn Co. v. United States (1981)',
    reason:
      'A confidential communication made for the purpose of obtaining legal advice, which is the core of the privilege.',
  },
  rca: {
    survives: true,
    authority: 'In re Kellogg Brown & Root (2014)',
    reason:
      'Legal advice was one significant purpose of the review, so protection holds even though company policy also required it.',
    caveat:
      'This survives because entry was pre-committed and quantified, not asserted after the fact.',
  },
  liability: {
    survives: true,
    authority: 'In re Target (2015)',
    reason:
      'A counsel-led assessment, demonstrably separate from operational remediation and undertaken in anticipation of litigation.',
  },
  evaluator: {
    survives: true,
    authority: 'United States v. Kovel (1961)',
    reason:
      'An outside evaluator may enter as an agent of counsel where the work is genuinely necessary to counsel’s advice.',
    caveat:
      'Privilege does not attach merely because counsel arranged the engagement. If the evaluation would have been commissioned anyway, this claim fails.',
  },
  'jira-clean': {
    survives: false,
    authority: 'Guo Wengui v. Clark Hill (2021)',
    reason:
      'Remediation the firm would have carried out regardless is not privileged because counsel was involved in deciding to do it.',
  },
  'jira-dirty': {
    survives: false,
    authority: 'Guo Wengui v. Clark Hill (2021)',
    reason:
      'A work order is operational, not legal, and the causal assertion travelling inside it is produced along with the ticket.',
  },
  regulator: {
    survives: false,
    authority: 'In re Capital One (2020)',
    reason:
      'A report prepared to satisfy a regulatory duty serves a business and compliance function, and would have been produced in substantially similar form regardless.',
  },
  board: {
    survives: false,
    authority: "In re Rutter's (2021)",
    reason:
      'A briefing to the risk committee is corporate governance and a routine business activity, whatever counsel’s role in preparing it.',
  },
}
